# Generated by Django 5.0.4 on 2024-05-15 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_payment_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
